# Generated by Django 5.2.8 on 2025-11-12 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_products_vendorproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product-images/')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.ManyToManyField(related_name='products', to='firstapp.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.image'),
        ),
    ]
